version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logs
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '1'
          memory: 1GB
    healthcheck:
      test: curl -s http://0.0.0.0:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - logs
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
        reservations:
          cpus: '1'
          memory: 1GB
    healthcheck:
      test: curl -s http:///0.0.0.0:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  logs:
    driver: bridge

volumes:
  elasticsearch: